"""added pizza and choices models

Revision ID: 052e183b71d5
Revises: 
Create Date: 2018-09-21 12:04:23.531346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052e183b71d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=264), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pizza_title'), 'pizza', ['title'], unique=True)
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice_title', sa.String(length=32), nullable=True),
    sa.Column('choice_price', sa.Numeric(), nullable=True),
    sa.Column('pizza_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices')
    op.drop_index(op.f('ix_pizza_title'), table_name='pizza')
    op.drop_table('pizza')
    # ### end Alembic commands ###
