"""removed unique constraint at pizza.title

Revision ID: 7e3403c66c27
Revises: 052e183b71d5
Create Date: 2018-09-21 13:35:57.653882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3403c66c27'
down_revision = '052e183b71d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pizza_title', table_name='pizza')
    op.create_index(op.f('ix_pizza_title'), 'pizza', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pizza_title'), table_name='pizza')
    op.create_index('ix_pizza_title', 'pizza', ['title'], unique=1)
    # ### end Alembic commands ###
